/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.
 
 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
 // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void changehue(GCustomSlider source, GEvent event) { //_CODE_:hueslider:673720:
  //println("#"+hex(addcolor));
  //println("bright - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:hueslider:673720:

public void name_change(GTextField source, GEvent event) { //_CODE_:varname:506960:
  //println("varname - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:varname:506960:

public void saturationchange(GCustomSlider source, GEvent event) { //_CODE_:satslider:290355:
  //println("#"+hex(addcolor));
  //println("satslider - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:satslider:290355:

public void brightchange(GCustomSlider source, GEvent event) { //_CODE_:bright:770043:
  //println("#"+hex(addcolor));
  //println("bright - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:bright:770043:

public void button1_click1(GButton source, GEvent event) { //_CODE_:add:927848:
  if (names.indexOf(varname.getText())<0 && varname.getText()!="") {
    colors.add(addcolor);
    names.add(varname.getText());
  }
  //println("add - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:add:927848:

public void themenamechange(GTextField source, GEvent event) { //_CODE_:themename:503835:
  //println("themename - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:themename:503835:

public void submit_click(GButton source, GEvent event) { //_CODE_:submit:370142:
  //println("submit - GButton >> GEvent." + event + " @ " + millis());
  String[] lines = new String[names.size()];
  for (int i = 0; i < lines.length; i++) {
    lines[i] = names.get(i) + ":#" + hex(colors.get(i));
  }
  //println(lines);
  saveStrings(themename.getText() + ".thm", lines);
} //_CODE_:submit:370142:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI() {
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  hueslider = new GCustomSlider(this, 450, 150, 300, 50, "blue18px");
  hueslider.setLimits(50.0, 0.0, 100.0);
  hueslider.setNumberFormat(G4P.DECIMAL, 2);
  hueslider.setOpaque(false);
  hueslider.addEventHandler(this, "changehue");
  varname = new GTextField(this, 450, 50, 300, 50, G4P.SCROLLBARS_NONE);
  varname.setPromptText("Variable Name");
  varname.setOpaque(true);
  varname.addEventHandler(this, "name_change");
  satslider = new GCustomSlider(this, 450, 200, 300, 50, "blue18px");
  satslider.setLimits(50.0, 0.0, 100.0);
  satslider.setNumberFormat(G4P.DECIMAL, 2);
  satslider.setOpaque(false);
  satslider.addEventHandler(this, "saturationchange");
  bright = new GCustomSlider(this, 450, 250, 300, 50, "blue18px");
  bright.setLimits(50.0, 0.0, 100.0);
  bright.setNumberFormat(G4P.DECIMAL, 2);
  bright.setOpaque(false);
  bright.addEventHandler(this, "brightchange");
  add = new GButton(this, 475, 325, 100, 50);
  add.setText("Add Color");
  add.addEventHandler(this, "button1_click1");
  themename = new GTextField(this, 50, 50, 300, 50, G4P.SCROLLBARS_NONE);
  themename.setPromptText("Theme Name");
  themename.setOpaque(true);
  themename.addEventHandler(this, "themenamechange");
  submit = new GButton(this, 625, 325, 100, 50);
  submit.setText("Save Template");
  submit.addEventHandler(this, "submit_click");
}

// Variable declarations 
// autogenerated do not edit
GCustomSlider hueslider; 
GTextField varname; 
GCustomSlider satslider; 
GCustomSlider bright; 
GButton add; 
GTextField themename; 
GButton submit; 